# Generated by Django 2.1.4 on 2018-12-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scan.Subscription')),
            ],
        ),
    ]
