# Generated by Django 2.1.4 on 2019-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='qrcode',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='count_left',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
